alias esp='espeak-ng'
alias espfem='espeak-ng -v us1'
alias espru='espeak-ng -v ru'
alias espde='espeak-ng -v de'
alias espgr='espeak-ng -v el'
alias espla='espeak-ng -v la'

alias esp-voices='espeak-ng --voices'
alias esp-voices-mb='espeak-ng --voices=mb'
alias esp-voices-en='espeak-ng --voices=en'
alias esp-voices-ru='espeak-ng --voices=ru'
alias esp-voices-de='espeak-ng --voices=de'
alias esp-voices-gr='espeak-ng --voices=el'
alias esp-voices-la='espeak-ng --voices=la'

# alias esp-voices-gr='esp-voices|grep -i greek'
# alias esp-voices-la='esp-voices|grep -i latin'
